- hosts: base
  sudo: yes
  tasks:
    - name: be sure lv is installed
      apt: name=lv state=installed
    - name: be sure tmux is installed
      apt: name=tmux state=installed
    - name: be sure tmux.conf is exists
      copy: src=roles/base/files/tmux.conf dest=/root/.tmux.conf owner=root group=root mode=644
